### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lrvick** [AndroidHardening/chromium_patches#11]
MIT or similar would make it easy to include these in my builds and save me a lot of time trying to re-implement them :)

**Comment by thestinger** [comment]
I marked these patches as being under the MIT license so that should be fine now.

The hardened allocator is already under the MIT license and changes to existing Android repositories are also under permissive licenses. Only the Auditor app, AttestationServer and other repositories not currently included in the AndroidHardening platform_manifest like the PDF app and all the past hardening work are not under permissive licensing yet since that will require funding.
